Content-Type: application/json
Auth Type: Basic Auth
Username: userProviderApi
Password:Temenos@123!
companyId: US0010001
URL_CreateCustomer:https://americasbsgprd.temenos.com/irf-provider-container/api/v4.1.0/party/us/customers/individuals